-- MySQL Script generated by MySQL Workbench
-- Fri Nov 24 08:48:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tareasbd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tareasbd` ;

-- -----------------------------------------------------
-- Schema tareasbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tareasbd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tareasbd` ;

-- -----------------------------------------------------
-- Table `tareasbd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tareasbd`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tareasbd`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tareasbd`.`tareas` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha_hora_creacion` DATETIME NOT NULL,
  `fecha_hora_modificacion` DATETIME NOT NULL,
  `completada` TINYINT NOT NULL,
  PRIMARY KEY (`id_tarea`),
  INDEX `fk_usuario_tarea_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tarea`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tareasbd`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
