# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfazprincipal.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 550, 281, 16))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 270, 201, 21))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 270, 161, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 250, 211, 16))
        self.label_4.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 250, 211, 16))
        self.label_5.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 310, 111, 23))
        self.pushButton.setStyleSheet("font: 14pt \"Mongolian Baiti\";")
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 81, 16))
        self.label_7.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_7.setObjectName("label_7")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 360, 381, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 340, 211, 16))
        self.label_15.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 390, 211, 16))
        self.label_16.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 410, 381, 21))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 440, 211, 16))
        self.label_17.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(10, 460, 381, 21))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 210, 301, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(100, 190, 271, 16))
        self.label_18.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 490, 111, 23))
        self.pushButton_2.setStyleSheet("font: 14pt \"Mongolian Baiti\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(400, 0, 301, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setStyleSheet("background-color: rgb(141, 93, 93);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setStyleSheet("background-color: rgb(141, 93, 93);\n"
"color: rgb(255, 255, 255);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setStyleSheet("background-color: rgb(141, 93, 93);\n"
"color: rgb(255, 255, 255);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setStyleSheet("background-color: rgb(141, 93, 93);\n"
"color: rgb(255, 255, 255);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 240, 301, 21))
        self.pushButton_3.setStyleSheet("font: 14pt \"Mongolian Baiti\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(400, 270, 301, 181))
        self.label_19.setStyleSheet("font: 16pt \"MingLiU_HKSCS-ExtB\";\n"
"color: rgb(0, 0, 0);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 731, 581))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Fondo Gris claro.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 371, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Logo Gris.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 520, 321, 41))
        self.pushButton_4.setStyleSheet("font: 14pt \"Mongolian Baiti\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label.raise_()
        self.label_6.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton.raise_()
        self.label_7.raise_()
        self.comboBox_3.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.comboBox_4.raise_()
        self.label_17.raise_()
        self.comboBox_5.raise_()
        self.lineEdit.raise_()
        self.label_18.raise_()
        self.pushButton_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.pushButton_3.raise_()
        self.label_19.raise_()
        self.label_2.raise_()
        self.pushButton_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuZap_Store = QtWidgets.QMenu(self.menuArchivo)
        self.menuZap_Store.setObjectName("menuZap_Store")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.menuZap_Store.addAction(self.actionAcerca_de)
        self.menuArchivo.addAction(self.menuZap_Store.menuAction())
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Autor: Luis Enrique Gallardo Ramirez"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Zapatos"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Tennis"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Zapatos Ortopedicos"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "2-5"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "5-8"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "9-12"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "13-14"))
        self.label_4.setText(_translate("MainWindow", "Tipo de Calzado"))
        self.label_5.setText(_translate("MainWindow", "Talla"))
        self.pushButton.setText(_translate("MainWindow", "Siguiente"))
        self.label_7.setText(_translate("MainWindow", "Cliente:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "ZAPATO CASUAL DE PLAYA FLEXI    $1,199.00 MXN"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "SNEAKER MEZCLA DE TEXTURAS FLEXI    $1,299.00 MXN"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "ZAPATO OXFORD BOSTONIANO QUIRELLI    $1,499.00 MXN"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "ZAPATO CASUAL PARA OFICINA FLEXI    $1,099.00 MXN"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "ZAPATO OXFORD BOSTONIANO QUIRELLI    $1,499.00 MXN"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "ZAPATO CASUAL PARA OFICINA FLEXI    $1,099.00 MXN"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "ZAPATO DE VESTIR PARA SALIR FLEXI    $1,149.00 MXN"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "BOTA FLEXI COUNTRY PARA OUTDOOR     $1,499.00 MXN"))
        self.label_15.setText(_translate("MainWindow", "Zapatos"))
        self.label_16.setText(_translate("MainWindow", "Tennis"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "$1,899  Tenis Resonator Mid"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "$2,099  Tenis Classic Legacy AZ Looney Tunes™"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "$3,599  Tenis Instapump Fury Zone Looney Tunes"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "$2,499  Tenis Hurrikaze II Low Looney Tunes™"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "$1,599  Tenis Royal Techque T"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "$1,599  Tenis Essentials Royal Glide"))
        self.label_17.setText(_translate("MainWindow", "Zapatos Ortopedicos"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "NÁUTICO CLÁSICO DE PIEL QUIRELLI    $1,499.00 MXN"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "LOAFER CLÁSICO DE PIEL QUIRELLI    $1,499.00 MXN"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "SLIP ON LISO FLEXI    $1,249.00 MXN"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "LOAFER CON ANTIFAZ FLEXI    $1,199.00 MXN"))
        self.label_18.setText(_translate("MainWindow", "EL NOMBRE DEBE CONTENER 2 NOMBRES MINIMO "))
        self.pushButton_2.setText(_translate("MainWindow", "Siguiente"))
        self.label_8.setText(_translate("MainWindow", "Producto:"))
        self.label_9.setText(_translate("MainWindow", "Precio Total"))
        self.label_10.setText(_translate("MainWindow", "Descuento"))
        self.label_11.setText(_translate("MainWindow", "Pedidos"))
        self.pushButton_3.setText(_translate("MainWindow", "Realizar Ticket"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/Fondos/Fondo Gris claro.jpg\"/></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Apartado de Empleados"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuZap_Store.setTitle(_translate("MainWindow", "Zap Store "))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de..."))
